title: Sanskar Gupta
description: Software Engineer who got upgraded with ML & AI skills and ready to track down all you requirements to build a interactive and demanding product. 
            With 2+ years of extensive full stack development in latest technologies like Spring Boot, NextJS, AWS, etc. integrated with ML models to make the product
            fully automated and provide the best of both worlds.
logo: /assets/img/sanskar.jpg
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman